### ISSUE TITLE
Display test instance and test suite names in web app

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#196] opened 2022-02-07 08:43 UTC
Display test instance and test suite names in web app.  I have registered a workflow via WorfklowHub and I'm only seeing the suite and instance IDs.  Here's the link:  https://app.lifemonitor.eu/workflow;uuid=5cfd69e0-64b3-013a-560a-005056ab5db4.

This issue has priority over #195

**Comment by simleo** [comment] 2022-02-07 16:11
See https://github.com/crs4/lifemonitor-web/issues/11

**Comment by simleo** [comment] 2022-02-07 16:13
@kikkomep I've marked this as a duplicate of https://github.com/crs4/lifemonitor-web/issues/11, but if this needs changes in the back-end we probably want to keep them both.

**Closed** 2022-02-10 12:21 UTC
Labels: bug, duplicate
